.TH ODBC 1 "2 December 2003"
.\" (C) Copyright 1999, 2003 Diomidis Spinellis.  All rights reserved.
.\" 
.\" Permission to use, copy, and distribute this software and its
.\" documentation for any purpose and without fee for noncommercial use
.\" is hereby granted, provided that the above copyright notice appear in
.\" all copies and that both that copyright notice and this permission notice
.\" appear in supporting documentation.
.\" 
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\" $Id: odbc.1,v 1.3 2006-03-21 07:09:57 dds Exp $
.\"
.SH NAME
odbc \- provide ODBC-based database access
.SH SYNOPSIS
\fBodbc\fP 
[\fB\-v\fP]
[\fB\-R\fP \fIRS\fP]
[\fB\-F\fP \fIFS\fP]
[\fB\-h\fP]
\fIDRVC stmt\fP
.SH DESCRIPTION
\fIOdbc\fP 
prints the results of an \fISQL select\fP command
run on any database for which an appropriate data source has been defined.
Two arguments must always be specified as part of the \fIodbc\fP invocation:
the data source driver connection string, and an SQL select statement.
All data types are currently output as text according to the default
driver-supplied data conversions.
By default fields are separated by  the tab character and records by a
newline.
The select statement specified must conform to the syntax and conventions used
by the database being accessed.
.LP
The driver connection string can either specify a registered system data source
driver name, as in:
.br
        "DSN=registered_dsn_name;uid=myusername;pwd=mypassword"
.br
or directly a driver, as in:
.br
        "Driver={Microsoft Access Driver (*.mdb)};DBQ=c:\\db\\myfile.mdb"
.br
Data source drivers are typically configured through the
control panel (ODBC category or through the Administrative Tools menu).

.SH OPTIONS
.IP "\fB\-R\fP \fBRS\fP"
Specify the record separator used to delimit records on output.
The default record separator is a newline.
.IP "\fB\-F\fP \fBFS\fP"
Specify the field separator used to delimit fields on output.
The default field separator is a tab.
.IP "\fB\-h\fP"
The first line of the output will contain the name of each database field.

.SH EXAMPLE
mail `odbc DSN=userDB "select email from users"` <message
.br
Extracts the email address from all records from the table \fIusers\fP
which is part of the database \fIuserDB\fP and sends them the file
\fImessage\fP by email.
.SH "SEE ALSO"
D. Spinellis.  Outwit: Unix tool-based programming meets the Windows world.
In \fIUSENIX 2000 Technical Conference Proceedings\fP, San Diego, CA, USA,
June 2000, USENIX Association.
.br
International Organization for Standardization, Geneva, Switzerland.
\fIInformation technology \(em Database languages \(em SQL \(em Part 3:
Call-Level Interface (SQL/CLI)\fP, 1995.
ISO/IEC 9075-3:1995.
.br
Microsoft Developer Network Library,
ODBC API Reference,
the `Comments' section of the \fISQLDriverConnect\fP function.
.SH AUTHOR
(C) Copyright 1999-2003 Diomidis Spinellis.  All rights reserved.
.LP
Permission to use, copy, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
.LP
THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.SH BUGS
The presentation of results in textual format depends on the implementation of
the ODBC driver.
