.TH WINCLIP 1 "27 February 2004"
.\" (C) Copyright 1998-2004 Diomidis Spinellis.  All rights reserved.
.\" 
.\" Permission to use, copy, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and that
.\" both that copyright notice and this permission notice appear in
.\" supporting documentation.
.\" 
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\" $Id: winclip.1,v 1.7 2004-02-27 17:06:56 dds Exp $
.\"
.SH NAME
winclip \- console Windows clipboard interface
.SH SYNOPSIS
\fBwinclip\fP 
[\fB\-w\fP|\fB\-u\fP\fB\-m\fP]
[\fB\-b\fP]
\fB-c\fP|\fB-p\fP
[\fIfile\fP]
.SH DESCRIPTION
\fIWinclip\fP provides access to the Windows clipboard from a console
or MS-DOS window.
Its operation depends on its mandatory argument.
When executed with the -p (paste) argument it pastes
the Windows clipboard to its standard output or to the \fIfile\fP
optionally specified in the command line.
The \fIwinclip\fP output may be redirected
to a file (using the shell > syntax) or to another process
(using the shell | pipeline syntax).
When \fIwinclip\fP is executed with the -c (copy) argument
it copies its standard input (or the \fIfile\fP
optionally specified in the command line) to the Windows clipboard.
Again, \fIwinclip\fP input may be redirected to be read from a file
(using the < shell syntax), or from another process of a pipeline.
.LP
\fIWinclip\fP can currently paste text clipboard data, filenames
that have been copied in the Windows explorer, and bitmaps which
are pasted in binary \fIppm\fP format.
When tranfering text,
it will automatically perform the appropriate Windows to console
character code (OEM) set translations.
\fIWinclip\fP is an Intel architecture Win32 program that only works under 
the Intel processor versions of Windows NT, 95, 98, Me, 2000.
.SH OPTIONS
.IP "\fB\-c\fP"
Copy the standard input to the Windows clipboard.
.IP "\fB\-p\fP"
Copy the Windows clipboard contents to the standard output.
.IP "\fB\-w\fP"
Transfer text in the Windows-native format (CF_TEXT) instead of the
(default) DOS-native format (CF_OEMTEXT).
The Windows format is also known as ANSI text, but often represents
another Windows and locale-specific code page.
Setting this option will affect how non-ASCII characters will be encoded
for clipboard text and copied file icons.
.IP "\fB\-u\fP"
Transfer text in Unicode format (CF_UNICODETEXT) instead of the
(default) DOS-native format (CF_OEMTEXT).
The Unicode encoding is the same as the one used by the Windows clipboard:
apparently UCS-16 in little-endian byte order (UTF-16LE).
Setting this option will affect how non-ASCII characters will be encoded
for clipboard text and copied file icons.
.IP "\fB\-m\fP"
Transfer text in Unicode format (CF_UNICODETEXT) instead of the
(default) DOS-native format (CF_OEMTEXT).
The Unicode encoding is UTF-8.
Setting this option will affect how non-ASCII characters will be encoded
for clipboard text and copied file icons.
.IP "\fB\-b\fP"
When outputing Unicode text,
prepend a byte order mark (BOM) at the beginning.
This may make it easier for outher tools to recognize \fIwinclip\fP's
output format.
When reading data for the clipboard, automatically detect
Unicode data, and set the encoding and endianess, if a byte-order-mark is
detected.
.SH EXAMPLE
dir /b | winclip -c
.br
Copies the directory list to the Windows clipboard.
.LP
winclip -p file.txt
.br
Saves the Windows clipboard to file.txt.
.LP
winclip -p | perl -pe "tr/[A-Z]/[a-z]/" | winclip -c
.br
Converts the contents of the Windows clipboard to lowercase.
.SH "SEE ALSO"
D. Spinellis.  Outwit: Unix tool-based programming meets the Windows world.
In \fIUSENIX 2000 Technical Conference Proceedings\fP, San Diego, CA, USA,
June 2000, USENIX Association.

.SH AUTHOR
(C) Copyright 1994-2004 Diomidis Spinellis.  All rights reserved.
.LP
Permission to use, copy, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
.LP
THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.SH BUGS
Should handle more clipboard content types.
.LP
\fIWinclip\fP may not work as expected if the code page of the console
window it is running is different from the code page of the clipboard
data or the code page it is specified to use.
You can check and change a console code page using the \fIchcp\fP command.
